### ISSUE TITLE
Release patches

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/sphinxcontrib-confluencebuilder#152]
@jdknight there’s quite a few changes since the last update, think it’s time we release another stable version

**Comment by jdknight** [comment]
@tonybaloney, sounds good to me. Want me to run through a series of tests on actual Confluence instances?

I might suggest that the following issues/pull requests get resolved first for a release:

- [ ] Pull request #153 (to fix current test issue with Sphinx 1.8)
- [ ] Pull requests #147 and #151 can be re-tested once pull request #153 is in (builds can be re-invoked; I expect no issues).
- [ ] I should be able to rebase pull request #142 this week (if you want it in the release).
- [ ] It might be good to also resolve issue #149 (there is a fix mentioned in the comments; but a fix needs to be added into a commit and submitted).

That being said, I will leave the decision to you on how you want to proceed.

**Comment by tonybaloney** [comment]
rebased #142 and merged the other PRs. If you get time to look at #149, otherwise can mark as known issue in release

**Comment by jdknight** [comment]
Pull request #154 has been added to address concerned mentioned in issue #149.

I have also added two additional pull request for your consideration for the upcoming release:

- feature/re-enable-contents-unit-test | #155
- recommended-pre-release-cleanup | #156

You may want to take a look at the comments in issue #116 as well.

Note, I have done a quick validation test on Confluence Cloud and Confluence Server 6.0.6 and everything appears to be fine. If you want to go ahead with the release, that works for me. I will see if I can spare some time to do a full validation test against each support Confluence version. If I get results before the release, I will notify any issue here; if it occurs after the release, I will generate new issues (if needed.)

**Comment by jdknight** [comment]
Closing in lieu of #171.
