### ISSUE TITLE
prepare a v0.6 release

### ISSUE THREAD

**Issue by jdknight** [tonybaloney/sphinxcontrib-confluencebuilder#18]
The following issue captures the overall intent to release v0.6 of the `sphinxcontrib-confluencebuilder` module. This includes issues and more found under [0.6 milestone](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/milestone/1).

Before this release is made, the following tests are desired to be performed]

Owner/Contributor Todos:
- [X] Re-test proxy for both REST and XML-RPC APIs (ced564581ab6640f5a29cc23b8b0e9a4acd606c6).
- [X] Document `confluence_publish_prefix` in `README` (e55db2935220a879fd0f7f737b7e870263375d73).
- [X] Cleanup page-prefix support to not render prefix in the visible link name (only in the link path) (8525fc63fdc8eaae64bd631229f4a4dee221bb35).
- [X] Re-test page-prefix support (1e525b7ac9dc1927915b9604e31e9c4a900a1735).
-  Validate the changes in [devwork-moving-pineapple](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/commits/devwork-moving-pineapple) branch work after all above issues have been addressed as well as other milestone issues. Test using the following Confluence variants:
   - REST API Publishing and Purging
     - [X] Confluence Server 5.6.6
     - [x] Confluence Server 5.8.18
     - [x] Confluence Server 5.10.8
     - [X] Confluence Server 6.0.6
     - [x] Confluence Server 6.1.0
     - [X] Confluence Cloud
   - XML-RPC Publishing and Purging
     - [X] Confluence Server 4.1.10
     - [X] Confluence Server 5.6.6
     - [x] Confluence Server 5.8.18
     - [x] Confluence Server 5.10.8
     - [X] Confluence Server 6.0.6
     - [x] Confluence Server 6.1.0
     - [X] Confluence Cloud

Owner Todos:
- [x] Merge in [devwork-moving-pineapple](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/commits/devwork-moving-pineapple) on review accepted (see #20); or,
- [x] (optional) Merge in [devwork-link-support-rework](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/tree/devwork-link-support-rework) on review accepted (see #21).
- [x] (optional) Merge in [usability-improvements](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/tree/usability-improvements) on review accepted (see #22).
- [x] (major) Merge in [revert "publisher: ensure used space name is uppercase"](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/pull/23) on review accepted  (see #23)

Final Todos:
- [x] Update `CHANGES.rst` with release date.
- [x] Bumpversion to `release` (with tag) (see: 477f75810367d0b80576eafe4888bc5f0116fb5e)
- [ ] Bumpversion to `minor`.
- [x] Push release cycle commits and tag to `origin/master`.
- [x] From release tag, build and publish to PyPI (using `twine`).
- [ ] Close this issue.

_Edit: Updated checklist (2017-04-17)._

**Comment by jdknight** [comment]
I've performed all the desired tests I was hoping to complete for this development cycle. I'm still hoping that #21 and #22 get merged in before this release.

**Comment by tonybaloney** [comment]
@jdknight everything is merged. we good to go?

**Comment by jdknight** [comment]
@tonybaloney Was just doing some final tests; notice a big issue with the REST API and space casing (address in 2784bf512022d2b48d929e75839b7e449cdbe308). If we can pull in MR #23, we should be good to go.

**Comment by jdknight** [comment]
@tonybaloney, for this release, how do you want to proceed?

Normally I would update changes, version, etc. on the `master` branch; however, it's locked to only you (which is fair). There are a couple of ways we can handle this, and I'd leave it up to you to decide on how you want to proceed.

1.  You can performed the "Final Todos" yourself on the `master` branch (I can do the PyPI step if you want to skip it).
2. I can make a branch with the changes listed in "Final Todos" and let you do a fast-forward merge of the changes outside GitHub (unless GitHub UI supports it?). From there, I can do the tag/PyPI work after if you want.
3. I can submit a normal merge request and have you pull it in in the standard non-FF fashion; which will result in the tag not visually represented on the `master`'s linear history.

Unless you have another suggestion?

I usually aim for something like this:
```
 master  A-------E-------I-RELNOTES-RELVER-DEVER
          \     /       /                       \
 feature   B-C-D       /                         J
                \     /
 feature         F-G-H
```

**Comment by tonybaloney** [comment]
I can't see an obvious way to do it. I'll bump the versions and you can do the PyPi release?

**Comment by jdknight** [comment]
I'm for.

**Comment by tonybaloney** [comment]
I won't get time to complete it until later on today, it's early morning here now

**Comment by jdknight** [comment]
No rush by me -- only do it if you have the time.

**Comment by tonybaloney** [comment]
done my part tag hash is a0975997166398c02fba3d57a5133a6c6fa00c27

**Comment by tonybaloney** [comment]
The commands I normally use for the last bit are:
```bash
rm -f dist/*
python setup.py sdist bdist_wheel
twine upload dist/*
```
@jdknight

**Comment by jdknight** [comment]
@tonybaloney thanks! I'll try the PyPi update now.

**Comment by jdknight** [comment]
I've updated the PyPi package. I was able to download the `v0.6` version and use it with my current sample set.

@tonybaloney, if you're able to bump to a development cycle (bumpversion `minor`; if you don't mind), that would be cool. :)

**Comment by tonybaloney** [comment]
done. this can be closed now. Thanks for your help!

**Comment by jdknight** [comment]
Thanks as well.

`v0.6` released!
